#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=8:00:00
#PBS -N topup_eddy
#PBS -l vmem=8gb
#PBS -V

#module load cuda/8.0 #for bridges

# needs mrtrix3 container for eddy_openmp
# in case cuda version fails
export SINGULARITYENV_OMP_NUM_THREADS=$OMP_NUM_THREADS

# pass cuda91 path to singularity
export SINGULARITYENV_CUDA91PATH=$CUDA91PATH

time singularity exec -e --nv docker://brainlife/mrtrix3:3.0_RC3 ./pre_topup_preproc.sh
time singularity exec -e --nv docker://brainlife/mrtrix3:3.0.2 ./topup_eddy.sh
time singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./createRegressorsTSV.py
